config/routes.rb
Rails.application.routes.draw do

  resources :medicines
  resources :examinations
  resources :treatment_factors
  resources :diagnoses
  resources :specialists
  resources :abdominal_conditions
  resources :liver_conditions
  resources :effleurage_options
  resources :subcutanious_fat_options
  resources :postural_pose_options
  resources :general_state_options
  resources :constitution_options

  authenticated :doctor do
    root to: 'patients#index_for_doctor', as: :authenticated_root
  end
  root to: redirect('/doctors/sign_in')

  devise_for :doctors

  mount RailsAdmin::Engine => '/manage', as: 'rails_admin'

  get 'static_pages/help'

  get 'static_pages/about'

    resources :doctors do
      resources :patients do
        resources :visits
      end
    end

    get '/doctors/:doctor_id/visits', to: 'visits#index', as: 'doctor_visits'
    get '/doctors/:doctor_id/visits/build_report', to: 'visits#build_report', as: 'doctor_visits_build_report'
    get '/doctors/:doctor_id/visits/all_records', to: 'visits#all_records', as: 'doctor_visits_all_records'
    post '/doctors/:doctor_id/visits/add_to_report' => 'visits#add_to_report', as: 'doctor_visits_add_to_report'
    get '/doctors/:doctor_id/patients/:patient_id/generate_pdf' => 'patients#generate_pdf', as: 'doctor_patient_generate_pdf'
    get '/doctors/:doctor_id/visits/generate_pdf' => 'visits#generate_pdf', as: 'doctor_visits_generate_pdf'
    get '/doctors/:doctor_id/visits', to: 'visits#repeated_items_popup', as: 'doctor_visits_repeated_items_popup'
    get '/doctors/:doctor_id/patients/:patient_id/visits/new/add_final_diagnosis' => 'visits#add_final_diagnosis', as: 'doctor_patient_visits_new_add_final_diagnosis'
    get '/doctors/:doctor_id/patients/:patient_id/visits/new/add_dispanserisation' => 'visits#add_dispanserisation', as: 'doctor_patient_visits_new_add_dispanserisation'

end

app/models/visit.rb
class Visit < ActiveRecord::Base

  UNRANSACKABLE_ATTRIBUTES = ["id", "updated_at", "anamnesis", "allerg", "patient_id",
   "doctor_id", "constitution_option_id", "general_state_option_id", "postural_pose_option_id",
   "subcutanious_fat_option_id", "from_id", "effleurage_option_id", "height", "weight", "temp", "next",
   "general_state", "diagnosis", "created_at", "next", "complaints"]

  def self.ransackable_attributes auth_object = nil
    (column_names - UNRANSACKABLE_ATTRIBUTES) + (_ransackers.keys)
  end

  # ransacker :bool_test do
  #   Arel.sql("to_char(\"#{table_name}\".\"bool_test\", '99999')")
  # end

  ransacker :next do
    Arel.sql("TO_CHAR(next, 'DD.MM.YYYY')")
  end

  ransacker :id do
    Arel.sql("to_char(id, '9999999')") 
  end


  ransacker :created_at do
    Arel::Nodes::SqlLiteral.new("date(visits.created_at)")
  end

  ransacker :next do
    Arel::Nodes::SqlLiteral.new("date(visits.next)")
  end


  # ransacker :from do
  #   specialists  = Arel::Table.new(:specialists, ActiveRecord::Base)
  #   Visit.joins(:specialist).where(specialists[:id].eq(from_id))
  # end

  belongs_to :patient
  belongs_to :doctor

  has_many :specialists, through: :consultations
  has_many :consultations

  belongs_to :from, :class_name => 'Specialist'
  belongs_to :constitution_option
  belongs_to :general_state_option
  belongs_to :postural_pose_option
  
  has_many :concomitant_diagnoses, through: :concomitant_diagnosis_visits
  has_many :concomitant_diagnosis_visits
  has_many :complication_diagnoses, through: :complication_diagnosis_visits
  has_many :complication_diagnosis_visits
  has_many :primary_diagnoses, through: :primary_diagnosis_visits
  has_many :primary_diagnosis_visits


  has_many :condition_values, through: :condition_visits
  has_many :condition_visits #, :dependent => :destroy

  has_many :anamnesis_values, through: :anamnesis_visits
  has_many :anamnesis_visits

  has_many :treatment_factors, through: :treatments
  has_many :treatments, :dependent => :destroy

  has_many :examinations, through: :examination_results
  has_many :examination_results, :dependent => :destroy

  has_many :medicines, through: :medications
  has_many :medications, :dependent => :destroy

  accepts_nested_attributes_for :specialists
  accepts_nested_attributes_for :primary_diagnoses
  accepts_nested_attributes_for :concomitant_diagnoses
  accepts_nested_attributes_for :complication_diagnoses
  # accepts_nested_attributes_for :condition_visits, :allow_destroy => true
  accepts_nested_attributes_for :condition_values
  accepts_nested_attributes_for :anamnesis_values
  accepts_nested_attributes_for :treatments, :allow_destroy => true
  accepts_nested_attributes_for :medications, :allow_destroy => true
  accepts_nested_attributes_for :examination_results, :allow_destroy => true
  accepts_nested_attributes_for :examinations
  #accepts_nested_attributes_for :liver_condition_visits
  #validates :doctor_id, presence:true
  #validates :patient_id, presence:true

  acts_as_taggable # Alias for acts_as_taggable_on :tags
  acts_as_taggable_on :complaints

end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController

  before_action :set_visit, only: [:show, :edit, :update, :destroy]
  before_action :set_params

  @@report_hash = Hash.new


  @@ri = ReportItem.order("created_at").last
  @@vertical_counter = 0


  def set_params
    #logger.debug "before set params param #{@@param.inspect} all #{@@all}"
    @@param ||= Hash.new
    @@all ||= 0
    logger.debug "after set params param #{@@param.inspect} all #{@@all}"
  end
  # GET /visits
  # GET /visits.json
  def index
    @doctor = Doctor.find(params[:doctor_id])
    visits = @doctor.visits

    if (params[:patient_id])
      @patient = Patient.find(params[:patient_id])
      visits = @patient.visits
    end

    @q = visits.search(params[:q]);
    @visits = @q.result(distinct: true)#.includes(:treatments, :primary_diagnosis_visits).joins(:treatmentsrj)
                        #.includes(:primary_diagnosis_visits).joins(:primary_diagnosis_visits)
    @q.build_condition
    # @visits = @q.result.includes(:department, :employees)

    @param = params[:q]
    @all = @visits.count
    @@all = @all
    logger.debug "index all #{@@all}"
    @@param = @param
    @first = 10
    @second = 20
    @arr = [10, 20, 30]

    if !ReportItem.roots.first
      @ri = ReportItem.find_or_create_by(name: "Отчет") do |x|
        x.quantity = -1
        x.horizontal_counter = 0
        x.full_name = "Отчет"
      end
      @ri = @ri.children.find_or_create_by(name: "Всего") do |x|
        x.quantity = @all
        x.horizontal_counter = 0
        @@vertical_counter = 1
        x.full_name = "Всего"
      end

    end

    @ri = ReportItem.order("created_at").last
    @@ri = @ri

    #ri = @ri.children.create(name: "1", quantity: @all)

  end

  def add_final_diagnosis
    @doctor = current_doctor
    @patient = Patient.find(params[:patient_id])
    @final_diagnosis_list = FinalDiagnosisList.new

    #@visit = Visit.find(params[:id])

    respond_to do |format|
      format.js #add_question.js.erb
    end
  end

  def add_dispanserisation
    @doctor = current_doctor
    @patient = Patient.find(params[:patient_id])
    @dispanserisation = Dispanserisation.new
    #@visit = Visit.find(params[:id])

    respond_to do |format|
      format.js #add_question.js.erb
    end
  end

  def generate_pdf

      #@doctor = current_doctor
      #@patient = Patient.find(params[:patient_id])
      #@visits = @patient.visits.all

      respond_to do |format|
      format.html
      format.pdf do
        render :pdf => "report",   # Excluding ".pdf" extension.
          :disposition => "inline",
          :template => "visits/generate_pdf.pdf.erb",
          :layout => "pdf_layout.html",
          :locals => {}
      end
    end
  end

  def name(a)

    logger.debug "a in name #{a}"

    @name = "поле "
    @name +=  I18n.t a.last.to_a.last.first.second.first.second["name"].to_s, scope: 'report'
    @name += " "
    @name +=  t a.last.to_a.last["p"]
    @name += ' "'
    @name +=  a.last.to_a.last["v"].first.second.first.second
    @name += '" '
  end

  def fullname(a)
    @full_name = ""

    logger.debug "A #{a}"

    a.each { |x|
      @full_name += "поле "
      @full_name += I18n.t x.last.to_a.first.second.first.second["name"].to_s, scope: 'report'
      @full_name += " "
      @full_name += t x.last.to_a.second.last.to_s
      @full_name += ' "'
      @full_name += x.last.to_a.last.last.first.second.first.second.to_s
      @full_name += '" '
      @full_name += " и "
    }
    @full_name.chomp!(" и ")
    logger.debug "full_name #{@full_name}"
    return @full_name
  end

  def array_from_params(p)
    name = ""
    if p.to_a.last.first != "c"
      name, predicate = p.to_a.last.first.split "_"
    end
    a = p["c"].to_a
    @last_name = a.last.last["a"]["0"]["name"]
    while @last_name == ""
      if a.count > 1
        a = a.first a.count - 1

        logger.debug "a #{a}"

        @last_name = a.last.last["a"]["0"]["name"] if a.last.last["a"]["0"]
      else
        if name != ""
          a = []
        end
        break
      end
    end
    a
    #a.push ["99", {"a"=>{"0"=>{"name"=>name}}, "p"=> predicate, "v"=>{"0"=>{"value"=>""}}}]
  end

  def add_to_report
    @doctor = Doctor.find(params[:doctor_id])
    visits = @doctor.visits

    if (params[:patient_id])
      @patient = Patient.find(params[:patient_id])
      visits = @patient.visits
    end

    @q = visits.search(params[:q]);
    @visits = @q.result(distinct: true)#.includes(:treatments, :primary_diagnosis_visits).joins(:treatmentsrj)
                        #.includes(:primary_diagnosis_visits).joins(:primary_diagnosis_visits)
    @q.build_condition

    logger.debug "Q #{@q.inspect}"
    # @visits = @q.result.includes(:department, :employees)

    @param = params[:q]
    @all = @visits.count
    logger.debug "add to report @all #{@all} @@all #{@@all}"
    @@all = @all if !defined? @@all && @all != 0
    logger.debug "add to report @@all #{@@all}"
    @param = @@param.to_s#.tr('"', "'")
    @ri = @@ri

    @@report_hash.merge!(@param => @@all)
    @report_hash = @@report_hash

    logger.debug " RI #{@@ri} "
    logger.debug " RI #{@@ri} QUANTITY  #{@ri.quantity} ALL #{@@all}"

    # firs_loop_visited = false
    # while @ri.quantity <= @@all do
    #   logger.debug " RI QUANTITY loop1 #{@ri.quantity}"
    #   @ri = @ri.parent
    #   @@vertical_counter -= 1
    #   firs_loop_visited = true
    #   if not (@ri && @ri.parent)
    #      break
    #   end
    # end

    # if !firs_loop_visited
    #   while @ri.quantity > @@all do
    #     logger.debug " RI QUANTITY loop2 #{@ri.quantity}"

    #     if @ri.children.first
    #       @ri = @ri.children.first
    #       @@vertical_counter += 1
    #     end
    #     if not (@ri && @ri.children.first)
    #        break
    #     end

    #   end
    # end

    # logger.debug " RI QUANTITY AFTER LOOP #{@ri.quantity}"

    #@name = "Поле "
    #@name += t @@param.first.second.first.second.first.second.first.second.first.second.to_s
    #@name += " "
    #@name += t @@param.first.second.first.second["p"]
    #@name += ' "'
    #@name += @@param.first.second.first.second["v"].first.second.first.second
    #@name += '" '

    #@name = @@param.to_unsafe_h.to_a.last.last.to_a.last.to_a.last

    # logger.debug "before last_name #{@@param}"
    # last_name = @@param.to_unsafe_h.to_a.last.last.to_a.last.to_a.last.first.second.first.second["name"].to_s if @@param != {}

    # logger.debug "before if param and empty #{@@param}"
    # logger.debug "before if param and empty #{last_name}"

    # if @@param && @@param != {} && (last_name != "" || (last_name == "" && @@param.to_a.last.last.to_a.count > 1) )

    #   @name = "Поле "

    #   logger.debug "inside if #{@@param}"

    #   if last_name == ""
    #     a = @@param.to_a.last.last.to_a.first @@param.to_a.last.last.to_a.count - 1
    #   else
    #     a = @@param.to_a.last.last.to_a
    #   end

    #   logger.debug "inside if after pop #{a}"

    #   @name +=  I18n.t a.last.to_a.last.first.second.first.second["name"].to_s, scope: 'report' if\
    #     a.last.to_a.last.first.second.first.second["name"].to_s != ""
    #   @name += " "
    #   @name +=  t a.last.to_a.last["p"]
    #   @name += ' "'
    #   @name +=  a.last.to_a.last["v"].first.second.first.second
    #   @name += '" '

    #   @full_name = ""
    # #@full_name += @@param.to_unsafe_h.to_a.first.to_a.last.to_a.to_s + " = "

    #   logger.debug "A #{a}"

    #   a.to_a.each { |x|
    #     #@full_name += x.last.to_a.last.to_a.last.first.second.first.second["name"].to_s
    #     #@full_name += x.last.to_a.last.to_a.last["p"].to_s
    #     #@full_name += x.last.to_a.last.to_a.last["v"].first.second.first.second.to_s
    #     current_name = ""
    #     @full_name += "Поле "
    #     current_name += "Поле "
    #     @full_name += I18n.t x.last.to_a.first.second.first.second["name"].to_s, scope: 'report' if\
    #       a.last.last.to_a.last.to_a.last.first.second.first.second["name"].to_s != ""
    #     current_name += I18n.t x.last.to_a.first.second.first.second["name"].to_s, scope: 'report' if\
    #       a.last.last.to_a.last.to_a.last.first.second.first.second["name"].to_s != ""
    #     @full_name += " "
    #     current_name += " "
    #     @full_name += t x.last.to_a.second.last.to_s
    #     current_name += t x.last.to_a.second.last.to_s
    #     @full_name += ' "'
    #     @full_name += x.last.to_a.last.last.first.second.first.second.to_s
    #     current_name += x.last.to_a.last.last.first.second.first.second.to_s
    #     @full_name += '" '
    #     current_name += '" '

    #     if a.count > 1
    #       temp_ri = ReportItem.where(name: "Всего", quantity: 52).order(:created_at).last
    #       if temp_ri
    #         @ri = temp_ri
    #       end
    #     end

    #     @full_name += " && "
    #   }
    #   @full_name.chomp!(" && ")

    #   if a.count > 1

    #   else
    #     @ri = ReportItem.roots.first.children.last.children.create(name: @name,
    #       full_name: @full_name, quantity: @@all)
    #   end
    #   @ri = @ri.patient

    # else
    #   @name = "Всего"
    #   @full_name = "Всего посещений"

    #   logger.debug "else"

    # end


    # if ReportItem.first.descendants.exists?(name: @name, full_name: @full_name)
    #   logger.debug " IF "
    #   @ri = ReportItem.find_by(name: @name, full_name: @full_name).siblings.create(name: @name,
    #         quantity: @@all, full_name: @full_name)
    # else
    #   @ri = @ri.children.create(name: @name, full_name: @full_name, quantity: @@all)
    # end

    # @repeated_items_popup = 0
    # ReportItem.where.not(id: ReportItem.group(:full_name, :quantity, :ancestry).pluck('max(report_items.id)')).each { |x|
    #   x.delete if x.is_childless?
    #   @repeated_items_popup += 1
    # }
    # @ri = ReportItem.order("created_at").last
    # #
    # counter = 0
    # ri.siblings.each do |s|
    #   s.horizontal_counter = counter

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/visits/_condition_fields.html.erb
<div class="field">
  <%= f.attribute_fields do |a| %>
    <%= a.attribute_select({ associations: 
    	[:specialists, :treatment_factors, :from, 
    		:concomitant_diagnoses, :complication_diagnoses, :primary_diagnoses,
    		:examination_results, :medicines, :condition_values]
    		},{:class => "form-control"}) %>
  <% end %>
  <%= f.predicate_select({},{:class => "form-control"}) %>
  <%= f.value_fields do |v| %>
    <%= v.text_field :value,{:class => "form-control"} %>
  <% end %>
  <%= link_to "Сбросить", '#', class: "remove_fields" %>
</div>

app/views/visits/_examination_result_fields.html.erb
<div class="form-group nested-fields"> 
  <div class="col-lg-10">
    <%= f.hidden_field :_destroy, :class => 'removable' %>
    <%= f.label "Обследование", :class => 'control-label col-lg-2' %>
    <%= f.collection_select(:examination_id, Examination.all, :id, :name, {:include_hidden => false}, {:multiple => false, :class => 'form-control'}) %>
    <br>
    <%= f.label "Результат", :class => 'control-label col-lg-2' %>
    <%= f.text_field :result, :class => 'form-control' %>
    <%= link_to_remove_association " Удалить ", f, :class => 'control-label col-lg-2' %>
  </div>
</div>

app/views/visits/_final_diagnosis_partial.html.erb
  <div class="form-group" id = "final-diagnosis">
    <%= l.label "Добавить диагноз в список уточненных диагнозов", :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= l.collection_select(:diagnosis_id, Diagnosis.all, :id, :name, {:include_hidden => false}, {:multiple => false, :class => 'form-control'}) %>
        Установлен повторно: <%= l.check_box :seconsary %>
        <!-- <%= l.hidden_field :doctor_id, :value => @doctor.id  %>
        <%= l.hidden_field :patient_id, :value => @patient.id  %> -->
      </div>

  </div>

app/views/visits/_medication_fields.html.erb
<div class="form-group nested-fields"> 
  <div class="col-lg-10">
    <%= f.hidden_field :_destroy, :class => 'removable' %>
    <%= f.label "Медикаментозное лечение", :class => 'control-label col-lg-2' %>
    <%= f.collection_select(:medicine_id, Medicine.all, :id, :name, {}, {:multiple => false, :class => "form-control"}) %>
    <br>
    <%= f.label "Дополнительно", :class => 'control-label col-lg-2' %>
    <%= f.text_field :details, :class => 'form-control' %>
    <%= f.label "Дозировка", :class => 'control-label col-lg-2' %>
    <%= f.text_field :dosage, :class => 'form-control' %>
    <%= f.label "Длительность", :class => 'control-label col-lg-2' %>
    <%= f.text_field :duration, :class => 'form-control' %>
    <%= link_to_remove_association " Удалить ", f, :class => 'control-label col-lg-2' %>
  </div>
</div>

app/views/visits/_visit.html.erb
<li id="visit-<%= visit.id %>">

  <span class="from"><b>From:</b> <%= link_to visit.from, doctor_patient_visit_path(current_doctor.id, @patient.id, visit.id)%> </span>

</li>

app/views/visits/add_dispanserisation.js.erb
<%
# @doctor = current_doctor
# @patient = Patient.find(params[:patient_id])
# @dispanserisation = Dispanserisation.new
fields_for @dispanserisation do |d|
  d.hidden_field :doctor_id, :value => @doctor.id
  d.hidden_field :patient_id, :value => @patient.id  
  @d = d
end
%>
$("#dispanserisation").html('<%= escape_javascript(render partial: "dispanserisation_partial", locals: { d: @d }) %> ');

app/views/visits/add_final_diagnosis.js.erb
<% fields_for @final_diagnosis_list do |l|
   l.hidden_field :doctor_id, :value => @doctor.id
   l.hidden_field :patient_id, :value => @patient.id
   @l = l
 end%>
$("#add-final-diagnosis").html('<%= escape_javascript(render partial: "final_diagnosis_partial", locals: { l: @l }) %> ');

app/views/visits/add_to_report.js.erb
$("#testdiv").html('<%= render partial: "report" %> ');
<% if @repeated_items_popup > 1 %>
	//sweetAlert("Awesome!");
	swal("Ой", "<%= @repeated_items_popup %> Такой пункт в отчете уже есть!", "error");
<% end %>

app/views/visits/all_records.js.erb
$("#visits-index-table").html('<%= escape_javascript(render partial: "all_records_partial") %>');

app/views/visits/build_report.js.erb
swal("Готово!", "Отчет очищен", "success");
$("#testdiv").html('<%= render partial: "report" %> ');

app/views/visits/edit.html.erb
<%- model_class = Visit -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/visits/generate_pdf.pdf.erb
<%= print_report(ReportItem.roots.first, 0) %>

app/views/visits/index.html.erb
<%- model_class = Visit -%>
<div class="page-header">
  <h1>Анализ посещений</h1>
  <%= link_to 'Получить PDF', doctor_visits_generate_pdf_path(format: :pdf, :method => :get)%>
</div>

<div id = "testdiv">
  <%= print_report(ReportItem.roots.first, 0) %>
</div> 

<%= search_form_for @q, url: doctor_visits_path do |f| %>
  <%= f.condition_fields do |c| %> 
    <%= render "condition_fields", f: c %>
  <% end %>
  <p><%= link_to_add_fields "Добавить условие", f, :condition %>
  <!-- <div class='radio'> -->
    <br>
    <%= f.label :secondary_true, 'Вторичный' %>
    <%= f.radio_button :secondary_true, 1, checked: false %><br>
    <%= f.label :secondary_false, 'Первичный' %>
    <%= f.radio_button :secondary_false, 1 %>
  <!-- </div> -->
  <div class="actions"><%= f.submit "Поиск", {:class => "btn"} %></div>
<% end %>
<br>
<%= link_to 'Добавить к отчету', doctor_visits_add_to_report_path, :method => :post, remote: true %>

<%= link_to 'Очистить', doctor_visits_build_report_path, :method => :get, remote: true %>
<div id = "report"><h3></h3></div>

<div id = "found" ><h4>Найдено: <%= @all %></h4></div>

<div style = "overflow-x: auto; width: 100%" id = "visits-index-table">
  <table class="table table-striped">
    <thead> 
      <tr>
        <th><%= t(:created_at) %></th>
        <th><%= t(:from_id) %></th>
        <th><%= t(:an_morbi) %></th>
        <th><%= t(:primary_diagnosis) %></th>
        <th><%= t(:concomitant_diagnosis) %></th>
        <th><%= t(:complication_diagnosis) %></th>
        <th><%= t(:examination) %></th>
        <th><%= t(:examination_result) %></th>
        <th><%= t(:consultation) %></th>
        <th><%= t(:treatment) %></th>
        <th><%= t(:medication) %></th>
        <th><%= I18n.t :secondary, scope: 'visits.index' %></th>
        <th><%= I18n.t :next, scope: 'visits.index' %></th>

        <th> id </th>

        <th> Данные осмотра: </th>

        <% @condition_headers = Array.new %>
        <% ConditionName.all.each do |name| %>

          <% @visit_has_value_of_this_name = false %>  

          <% name.condition_values.each do |value| %>
             
            <% @visits.each do |visit| %>

              <% if ConditionVisit.find_by(:condition_value_id => value.id, :visit_id => visit.id) %>

                <% @visit_has_value_of_this_name = true %>  

              <% end %>  
            <% end %> 
          <% end %> 
             
          <% if @visit_has_value_of_this_name %>
            <% @condition_headers << name %>
            
            <% @visit_has_value_of_this_name = false %>  
          <% end %> 

              <!-- <br> -->
          
        <% end %>
          <!-- <hr> -->

        <% @condition_headers.each do |h| %>
          <th><%= h.condition_type.name.to_s + ": " if h.condition_type.name != h.name %> 
            
            <%= h.name %></th> 
        <% end %>

      </tr>
    </thead>
    <tbody>
      <% @visits.last(15).each do |visit| %>
        <tr>
          <td><%= link_to visit.created_at.strftime("%d.%m.%Y"), doctor_patient_visit_path(@doctor,visit.patient,visit) %></td>
          <td><%= visit.from.name if visit.from %></td>
          <td><%= visit.an_morbi %></td>
          <td>
            <ul>
              <% visit.primary_diagnoses.each do |primary_diagnosis| %>
                <li><%= primary_diagnosis.name %></li>
              <% end %>
            </ul>
          </td>
          <td>
            <ul>
              <% visit.concomitant_diagnoses.each do |concomitant_diagnosis| %>
                <li><%= concomitant_diagnosis.name %></li>
              <% end %>
            </ul>
          </td>
          <td>
            <ul>
              <% visit.complication_diagnoses.each do |complication_diagnosis| %>
                <li><%= complication_diagnosis.name %></li>
              <% end %>
            </ul>
          </td>
          <td>
            <ul>
              <% @exs = Array.new %>
              <% @exs = ExaminationResult.where(:visit_id => visit.id, :result => nil).limit(nil) %>
              <% if @exs.any? %>
                <% @exs.each do |e| %>
                  <%= e.examination.name %> <br>
                <% end %>
              <% end %>
            </ul>
          </td>
          <td>
            <ul>
              <% @exs = Array.new %>
              <% @except = Array.new %>
              <% @exs =  ExaminationResult.where(:visit_id => visit.id).limit(nil) %>
              <% @except = ExaminationResult.where(:visit_id => visit.id, :result => nil).limit(nil) %>
              <% @exs -= @except %>
              <% if @exs.any? %>
                <% @exs.each do |e| %>
                  <% if e.examination %>
                    <%= e.examination.name%>: 
                    <%= e.result %>
                   <% end %>      
                <% end %>
              <% end %>
            </ul>
          </td>
          <td>
            <ul>
              <% visit.consultations.each do |consultation| %>
                <li><%= consultation.specialist.name if consultation.specialist %></li>
              <% end %>
            </ul>
          </td>
          <td>
            <ul>
              <% visit.treatments.each do |treatment| %>
                <li><%= treatment.treatment_factor.name if treatment.treatment_factor %></li>
              <% end %>
            </ul>
          </td>
          <td>
            <ul>
              <% visit.medications.each do |medication| %>
                <li><%= medication.medicine.name if medication.medicine %></li>
              <% end %>
            </ul>
          </td>
          <td>
            <% if visit.secondary == true %> Вторичный <% else %> Первичный 
            <% end %>
          </td>

          <td><%= visit.next.strftime("%d.%m.%Y") if visit.next %></td>

          <td> <%= visit.id %> </td>
            
          <td> <%#=@condition_headers %> </td>

          <% @condition_headers.each do |h| %>
            <% #dfghjk %>
            <td>
              
            <% h.condition_values.each do |v| %>
            <% #dfghjk %>
              <% visit.condition_values.each do |value| %>
              <% #dfghjk %>
                <% if value == v %>
                  <%= value.name %> <br>
                  <% #dfghjk %>
                <% end %>
              <% end %>
            <% end %>
            </td>
          <% end %>

        </tr>
      <% end %>
    </tbody>
  </table>
</div>


Показаны 15 последних записей. Для просмотра всех нажмите <%= link_to "сюда", doctor_visits_all_records_path, :remote => true %> (может занять несколько минут).
<hr>

<script>
$(document).ready(function() {
  NProgress.start();
});
</script>

app/views/visits/new.html.erb
<%- model_class = Visit -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'Новое посещение'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>