config/routes.rb
Rails.application.routes.draw do

  resources :medicines
  resources :examinations
  resources :treatment_factors
  resources :diagnoses
  resources :specialists
  resources :abdominal_conditions
  resources :liver_conditions
  resources :effleurage_options
  resources :subcutanious_fat_options
  resources :postural_pose_options
  resources :general_state_options
  resources :constitution_options

  authenticated :doctor do
    root to: 'patients#index_for_doctor', as: :authenticated_root
  end
  root to: redirect('/doctors/sign_in')

  devise_for :doctors

  mount RailsAdmin::Engine => '/manage', as: 'rails_admin'

  get 'static_pages/help'

  get 'static_pages/about'

    resources :doctors do
      resources :patients do
        resources :visits
      end
    end

    get '/doctors/:doctor_id/visits', to: 'visits#index', as: 'doctor_visits'
    get '/doctors/:doctor_id/visits/build_report', to: 'visits#build_report', as: 'doctor_visits_build_report'
    get '/doctors/:doctor_id/visits/all_records', to: 'visits#all_records', as: 'doctor_visits_all_records'
    post '/doctors/:doctor_id/visits/add_to_report' => 'visits#add_to_report', as: 'doctor_visits_add_to_report'
    get '/doctors/:doctor_id/patients/:patient_id/generate_pdf' => 'patients#generate_pdf', as: 'doctor_patient_generate_pdf'
    get '/doctors/:doctor_id/visits/generate_pdf' => 'visits#generate_pdf', as: 'doctor_visits_generate_pdf'
    get '/doctors/:doctor_id/visits', to: 'visits#repeated_items_popup', as: 'doctor_visits_repeated_items_popup'
    get '/doctors/:doctor_id/patients/:patient_id/visits/new/add_final_diagnosis' => 'visits#add_final_diagnosis', as: 'doctor_patient_visits_new_add_final_diagnosis'
    get '/doctors/:doctor_id/patients/:patient_id/visits/new/add_dispanserisation' => 'visits#add_dispanserisation', as: 'doctor_patient_visits_new_add_dispanserisation'

end

app/models/subcutanious_fat_option.rb
class SubcutaniousFatOption < ActiveRecord::Base
end

app/controllers/subcutanious_fat_options_controller.rb
class SubcutaniousFatOptionsController < ApplicationController
  before_action :set_subcutanious_fat_option, only: [:show, :edit, :update, :destroy]

  # GET /subcutanious_fat_options
  # GET /subcutanious_fat_options.json
  def index
    @subcutanious_fat_options = SubcutaniousFatOption.all
  end

  # GET /subcutanious_fat_options/1
  # GET /subcutanious_fat_options/1.json
  def show
  end

  # GET /subcutanious_fat_options/new
  def new
    @subcutanious_fat_option = SubcutaniousFatOption.new
  end

  # GET /subcutanious_fat_options/1/edit
  def edit
  end

  # POST /subcutanious_fat_options
  # POST /subcutanious_fat_options.json
  def create
    @subcutanious_fat_option = SubcutaniousFatOption.new(subcutanious_fat_option_params)

    respond_to do |format|
      if @subcutanious_fat_option.save
        format.html { redirect_to @subcutanious_fat_option, notice: 'Subcutanious fat option was successfully created.' }
        format.json { render :show, status: :created, location: @subcutanious_fat_option }
      else
        format.html { render :new }
        format.json { render json: @subcutanious_fat_option.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subcutanious_fat_options/1
  # PATCH/PUT /subcutanious_fat_options/1.json
  def update
    respond_to do |format|
      if @subcutanious_fat_option.update(subcutanious_fat_option_params)
        format.html { redirect_to @subcutanious_fat_option, notice: 'Subcutanious fat option was successfully updated.' }
        format.json { render :show, status: :ok, location: @subcutanious_fat_option }
      else
        format.html { render :edit }
        format.json { render json: @subcutanious_fat_option.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subcutanious_fat_options/1
  # DELETE /subcutanious_fat_options/1.json
  def destroy
    @subcutanious_fat_option.destroy
    respond_to do |format|
      format.html { redirect_to subcutanious_fat_options_url, notice: 'Subcutanious fat option was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subcutanious_fat_option
      @subcutanious_fat_option = SubcutaniousFatOption.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subcutanious_fat_option_params
      params.require(:subcutanious_fat_option).permit(:name)
    end
end

app/helpers/subcutanious_fat_options_helper.rb
module SubcutaniousFatOptionsHelper
end

app/views/subcutanious_fat_options/_form.html.erb
<%= form_for(@subcutanious_fat_option) do |f| %>
  <% if @subcutanious_fat_option.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subcutanious_fat_option.errors.count, "error") %> prohibited this subcutanious_fat_option from being saved:</h2>

      <ul>
      <% @subcutanious_fat_option.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subcutanious_fat_options/edit.html.erb
<h1>Editing Subcutanious Fat Option</h1>

<%= render 'form' %>

<%= link_to 'Show', @subcutanious_fat_option %> |
<%= link_to 'Back', subcutanious_fat_options_path %>

app/views/subcutanious_fat_options/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Subcutanious Fat Options</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subcutanious_fat_options.each do |subcutanious_fat_option| %>
      <tr>
        <td><%= subcutanious_fat_option.name %></td>
        <td><%= link_to 'Show', subcutanious_fat_option %></td>
        <td><%= link_to 'Edit', edit_subcutanious_fat_option_path(subcutanious_fat_option) %></td>
        <td><%= link_to 'Destroy', subcutanious_fat_option, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subcutanious fat option', new_subcutanious_fat_option_path %>

app/views/subcutanious_fat_options/new.html.erb
<h1>New Subcutanious Fat Option</h1>

<%= render 'form' %>

<%= link_to 'Back', subcutanious_fat_options_path %>

app/views/subcutanious_fat_options/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @subcutanious_fat_option.name %>
</p>

<%= link_to 'Edit', edit_subcutanious_fat_option_path(@subcutanious_fat_option) %> |
<%= link_to 'Back', subcutanious_fat_options_path %>