config/routes.rb
Rails.application.routes.draw do

  resources :medicines
  resources :examinations
  resources :treatment_factors
  resources :diagnoses
  resources :specialists
  resources :abdominal_conditions
  resources :liver_conditions
  resources :effleurage_options
  resources :subcutanious_fat_options
  resources :postural_pose_options
  resources :general_state_options
  resources :constitution_options

  authenticated :doctor do
    root to: 'patients#index_for_doctor', as: :authenticated_root
  end
  root to: redirect('/doctors/sign_in')

  devise_for :doctors

  mount RailsAdmin::Engine => '/manage', as: 'rails_admin'

  get 'static_pages/help'

  get 'static_pages/about'

    resources :doctors do
      resources :patients do
        resources :visits
      end
    end

    get '/doctors/:doctor_id/visits', to: 'visits#index', as: 'doctor_visits'
    get '/doctors/:doctor_id/visits/build_report', to: 'visits#build_report', as: 'doctor_visits_build_report'
    get '/doctors/:doctor_id/visits/all_records', to: 'visits#all_records', as: 'doctor_visits_all_records'
    post '/doctors/:doctor_id/visits/add_to_report' => 'visits#add_to_report', as: 'doctor_visits_add_to_report'
    get '/doctors/:doctor_id/patients/:patient_id/generate_pdf' => 'patients#generate_pdf', as: 'doctor_patient_generate_pdf'
    get '/doctors/:doctor_id/visits/generate_pdf' => 'visits#generate_pdf', as: 'doctor_visits_generate_pdf'
    get '/doctors/:doctor_id/visits', to: 'visits#repeated_items_popup', as: 'doctor_visits_repeated_items_popup'
    get '/doctors/:doctor_id/patients/:patient_id/visits/new/add_final_diagnosis' => 'visits#add_final_diagnosis', as: 'doctor_patient_visits_new_add_final_diagnosis'
    get '/doctors/:doctor_id/patients/:patient_id/visits/new/add_dispanserisation' => 'visits#add_dispanserisation', as: 'doctor_patient_visits_new_add_dispanserisation'

end

app/controllers/abdominal_conditions_controller.rb
class AbdominalConditionsController < ApplicationController
  before_action :set_abdominal_condition, only: [:show, :edit, :update, :destroy]

  # GET /abdominal_conditions
  # GET /abdominal_conditions.json
  def index
    @abdominal_conditions = AbdominalCondition.all
  end

  # GET /abdominal_conditions/1
  # GET /abdominal_conditions/1.json
  def show
  end

  # GET /abdominal_conditions/new
  def new
    @abdominal_condition = AbdominalCondition.new
  end

  # GET /abdominal_conditions/1/edit
  def edit
  end

  # POST /abdominal_conditions
  # POST /abdominal_conditions.json
  def create
    @abdominal_condition = AbdominalCondition.new(abdominal_condition_params)

    respond_to do |format|
      if @abdominal_condition.save
        format.html { redirect_to @abdominal_condition, notice: 'Abdominal condition was successfully created.' }
        format.json { render :show, status: :created, location: @abdominal_condition }
      else
        format.html { render :new }
        format.json { render json: @abdominal_condition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /abdominal_conditions/1
  # PATCH/PUT /abdominal_conditions/1.json
  def update
    respond_to do |format|
      if @abdominal_condition.update(abdominal_condition_params)
        format.html { redirect_to @abdominal_condition, notice: 'Abdominal condition was successfully updated.' }
        format.json { render :show, status: :ok, location: @abdominal_condition }
      else
        format.html { render :edit }
        format.json { render json: @abdominal_condition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /abdominal_conditions/1
  # DELETE /abdominal_conditions/1.json
  def destroy
    @abdominal_condition.destroy
    respond_to do |format|
      format.html { redirect_to abdominal_conditions_url, notice: 'Abdominal condition was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_abdominal_condition
      @abdominal_condition = AbdominalCondition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def abdominal_condition_params
      params.require(:abdominal_condition).permit(:name)
    end
end

app/helpers/abdominal_conditions_helper.rb
module AbdominalConditionsHelper
end

app/views/abdominal_conditions/_form.html.erb
<%= form_for(@abdominal_condition) do |f| %>
  <% if @abdominal_condition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@abdominal_condition.errors.count, "error") %> prohibited this abdominal_condition from being saved:</h2>

      <ul>
      <% @abdominal_condition.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/abdominal_conditions/edit.html.erb
<h1>Editing Abdominal Condition</h1>

<%= render 'form' %>

<%= link_to 'Show', @abdominal_condition %> |
<%= link_to 'Back', abdominal_conditions_path %>

app/views/abdominal_conditions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Abdominal Conditions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @abdominal_conditions.each do |abdominal_condition| %>
      <tr>
        <td><%= abdominal_condition.name %></td>
        <td><%= link_to 'Show', abdominal_condition %></td>
        <td><%= link_to 'Edit', edit_abdominal_condition_path(abdominal_condition) %></td>
        <td><%= link_to 'Destroy', abdominal_condition, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Abdominal condition', new_abdominal_condition_path %>

app/views/abdominal_conditions/new.html.erb
<h1>New Abdominal Condition</h1>

<%= render 'form' %>

<%= link_to 'Back', abdominal_conditions_path %>

app/views/abdominal_conditions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @abdominal_condition.name %>
</p>

<%= link_to 'Edit', edit_abdominal_condition_path(@abdominal_condition) %> |
<%= link_to 'Back', abdominal_conditions_path %>